### ISSUE TITLE
box-footprint template is too small.

### ISSUE THREAD

**Issue by choffee** [yorkhackspace/sh-topbox#1]
It looks like it is about a bearings width out on each box.
The one I printed looks to be be the same size as the one in the drawing in inkscape. Distance between the center of the end holes it looks to be 222mm but I think it needs to be about 4mm longer.

**Comment by aquila12** [comment]
It's possible I forgot to count the bearings.  Are they represented in the
drawing at all?

**Comment by choffee** [comment]
It looks like they are. There are little lines across the ends. That may not be it. I'll bring my calipers along tonight with all the parts and the template and we can have a look.

**Comment by aquila12** [comment]
Changed bearing design to reduce part count.  Measured parts; some appear to be very slightly oversized.
